version: '3'
services:
  api:
    build: .
    command: npm run dev
    ports:
    - "8082:8082"
    volumes:
    - ./:/usr/src/app
    env_file:
      - "env/api.env"
    links:
      - db
  db:
    image: mysql:5.7.26
    ports:
      - "3306:3306"
    env_file:
      - "env/db.env"
